server:
    port:
      8083
jwt:
  secret: secret

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/root"
    username: root
    password: root
